name: build

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.cshtml'
    - '**.css'

env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use

jobs:
  build:

    name: Build All Projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
        - Tutorial/1-Create a Razor Page
        - Tutorial/2-Add a model
        - Tutorial/3-Update Pages
        - Tutorial/4-Add Search
        - Final_Project

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Build Step - ${{ matrix.project }}
      run: dotnet build "${{ matrix.project }}/RazorPagesMovie/RazorPagesMovie.csproj"
